version: '3.3'
services:
  dfc-host-csharp:
    build: 
      context: .
      dockerfile: Scripts/Containers/dfc-host-csharp/Setup/Load/dockerfile
    image: ${project_name}--dfc-host-csharp
    hostname: dfc-host-csharp
    restart: always
    tty: true
    container_name: ${project_name}--dfc-host-csharp
    working_dir: /dfc-project/files
    volumes:
      - ./WorkFolder/Containers/dfc-host-csharp/Logs:/var/log:rw
      - ./WorkFolder/Containers/dfc-host-csharp/Files:/dfc-project/files:rw
      - ./WorkFolder/Containers/dfc-host-csharp/Configs/ClamAV:/etc/clamav:ro
      - ./WorkFolder/Containers/dfc-host-csharp/Configs/Neofetch:/home/dfc-user/.config/neofetch:ro
      - ./WorkFolder/Containers/Common/Firewall:/dfc-project/common/firewall:ro
      - ./WorkFolder/Containers/Common/Antivirus:/var/lib/clamav:ro
    ports:
      - 443:443
    networks:
      - dfc-net
    environment:
      - DISPLAY=host.docker.internal:0

networks:
  dfc-net:
    name: dfc-net--${project_name}
    driver: bridge